---
debug: false
headless: false
log_file: true
log:
  format: text
  level: info
login_url: "http://localhost:8888/login"
payloads:
  - "\"><img src=x onerror=prompt(1)>"
image_path: "./images/StoredXSS"
repo_path: "../caldera"
