---
debug: false
headless: true
log_file: true
log:
  format: text
  level: info
login_url: "http://localhost:8888/login"
sink_url: "http://localhost:8888/dh2cves2location.pathname?#home"
payloads:
  - '"><img src=x onerror=prompt(1)>'
image_path: "./images/StoredXSS"
repo_path: "../caldera"
